var app=angular.module('app',['ng', 'ngRoute', 'ngAnimate','ngTouch','ngCookies'])
.config(function($routeProvider){
	$routeProvider
	//首页
	.when("/",{
		templateUrl:"actity/huodong1.html",
		controller:"actitys",
	})
	.when("",{
		templateUrl:"actity/huodong1.html",
		controller:"actitys",
	})
	.when("/huodong1",{
		templateUrl:"actity/huodong1.html",
		controller:"actitys",
	})
	.when("/xindonghui",{
		templateUrl:"actity/xindonghui.html",
		controller:"xindonghui",
	})
	.when("/xindonghui2",{
		templateUrl:"actity/xindonghui2.html",
		controller:"xindonghui2",
	})
	.when("/buygood",{
		templateUrl:"actity/buygood.html",
		controller:"buygood",
	})
	.when("/midautumn",{
		templateUrl:"actity/midautumn.html",
		controller:"midautumn",
	})
	.when("/schoolseason",{
		templateUrl:"actity/schoolseason.html",
		controller:"schoolSeason",
	})
	.when("/cellmetting",{
		templateUrl:"actity/cellmetting.html",
		controller:"cellmetting",
	})
	.when("/lottery",{
		templateUrl:"actity/lottery.html",
		controller:"lottery",
	})
	.when("/sendGameSkin",{
		templateUrl:"actity/sendGameSkin.html",
		controller:"sendGameSkin",
	})
	.when("/redEnvelops",{
		templateUrl:"actity/redEnvelops.html",
		controller:"redEnvelops",
	})
	.when("/christmas",{
		templateUrl:"actity/christmas.html",
		controller:"christmas",
	})
	.when("/zhuanji",{
		templateUrl:"actity/zhuanji.html",
		controller:"zhuanji",
	})
	.when("/zhuanji02",{
		templateUrl:"actity/zhuanji/zhuanji02.html",
		controller:"zhuanji02",
	})
	.when("/zhuanji03",{
		templateUrl:"actity/zhuanji/zhuanji03.html",
		controller:"zhuanji03",
	})
	.when("/zhuanji04",{
		templateUrl:"actity/zhuanji/zhuanji04.html",
		controller:"zhuanji04",
	})
	.when("/zhuanji05",{
	templateUrl:"actity/zhuanji/zhuanji05.html",
	controller:"zhuanji05",
	})
	.when("/zhuanji06",{//如何分辨血清
	templateUrl:"actity/zhuanji/zhuanji06.html",
	controller:"zhuanji06",
	})
	.when("/yearsActivity",{
		templateUrl:"actity/yearsActivity.html",
		controller:"yearsActity",
	})
	.when("/levyLogo",{
		templateUrl:"actity/levyLogo.html",
		controller:"levyLogo",
	})
	.when("/newYears",{
	templateUrl:"actity/newYears.html",
	controller:"newYears",
	})
	.when("/valentinesDay",{
	templateUrl:"actity/valentinesDay.html",
	controller:"valentinesDay",
	})
	.otherwise({
	    redirectTo: "/"
	})
})